# Generated by Django 6.0.5 on 2026-05-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Empleado')),
                ('nombre', models.CharField(help_text='Nombre completo del empleado', max_length=100, verbose_name='Nombre')),
                ('departamento', models.CharField(help_text='Departamento del empleado', max_length=100, verbose_name='Departamento')),
                ('sueldo', models.DecimalField(decimal_places=2, help_text='Sueldo del empleado', max_digits=10, verbose_name='Sueldo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['idEmpleado'],
            },
        ),
    ]
